apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "f061e6e3-7e4d-4009-a7fd-a10ee3ce86f5"
      - op: replace
        path: /spec/parameters/tenantId
        value: "0ea3b3a9-cb85-4c2f-b819-e7697a800bef"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsstaging.blob.core.windows.net/customer1"
