apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "fe52d074-6a4c-4a30-b6da-b14dd80715b9"
      - op: replace
        path: /spec/parameters/tenantId
        value: "0ea3b3a9-cb85-4c2f-b819-e7697a800bef"
